### ISSUE TITLE
heat conductivity and specific heat

### ISSUE THREAD

**Issue by vivelakorea** [rhdodds/warp3d#13]
Hi, 

I'm trying to make a abaqus model same as the example 1 in the manual. 
Because there is a thermal load, so the specific heat and thermal conductivity of the material have to be defined in material's property in abaqus. But there are no values relating to these in the input file provided in the manual.

Is there some defualt values in warp3d?

Thanks.

**Comment by rhdodds** [comment]
Hello.

WARP3D does not have the capability to compute the steady or
transient temperature distribution in a model.

The user can input temperatures at model nodes computed from
another program. WARP3D then computes the strains and stresses
(linear or nonlinear) caused by the specified temperature distribution.

Best,

Bob Dodds

**Comment by vivelakorea** [comment]
I'm not sure I'm understanding it now.
Does it mean that heat does not transfer in WARP3D?

**Comment by rhdodds** [comment]
That is correct.

WARP3D does *not* perform heat transfer computations.

**Comment by vivelakorea** [comment]
Thanks for your kind explanation.
